// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Dl62LNC8p-zmihdWrkXzAyU1ZB3pldc',
    appId: '1:815933044394:web:180378f447b2bac02c02d3',
    messagingSenderId: '815933044394',
    projectId: 'journal-e3e8d',
    authDomain: 'journal-e3e8d.firebaseapp.com',
    storageBucket: 'journal-e3e8d.appspot.com',
    measurementId: 'G-CSY6T3DXBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_bII1fFKApUPMNN0pRJ4A7zpepRoWog',
    appId: '1:815933044394:android:0268b790852acfc62c02d3',
    messagingSenderId: '815933044394',
    projectId: 'journal-e3e8d',
    storageBucket: 'journal-e3e8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcaAGJi-Rs53QxYfIftc6Om_qWMA18MLs',
    appId: '1:815933044394:ios:be38ec5f0376debf2c02d3',
    messagingSenderId: '815933044394',
    projectId: 'journal-e3e8d',
    storageBucket: 'journal-e3e8d.appspot.com',
    iosBundleId: 'com.example.ch15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcaAGJi-Rs53QxYfIftc6Om_qWMA18MLs',
    appId: '1:815933044394:ios:c69ab86cde5505de2c02d3',
    messagingSenderId: '815933044394',
    projectId: 'journal-e3e8d',
    storageBucket: 'journal-e3e8d.appspot.com',
    iosBundleId: 'com.example.ch15.RunnerTests',
  );
}
